name: Publish Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if:  startsWith(github.head_ref, 'release/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Project (if present)
        run: npm run build --if-present

      - name: Get version
        id: get-version
        run: echo ::set-output name=version::$(node -p "require('./package.json').version")

      - name: Publish github
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: v${{ steps.get-version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish npmjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
