name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm test
      - run: npm run build
      - run: npm publish --tag=$(node -p "require('./package.json').version.match(/[0-9]+\.[0-9]+\.[0-9]+(-(.+)\.[0-9]+)?/)[2] || 'latest'")
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Update Documentation Site
        run: |
          repo_owner="gplint"
          repo_name="gplint.github.io"
          event_type="trigger-workflow"
          version=$(node -p "require('./package.json').version")

          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/gplint/$repo_name/dispatches \
          -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"

