name: Update Documentation Site

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish Release"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Update Documentation Site
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.PAT}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/gplint/gplint.github.io/dispatches \
          -d "{\"event_type\": \"deploy-documentation-site\", \"client_payload\": {\"unit\": false, \"integration\": true}}"
