name: Update Docs Site

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish Release"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Update Documentation Site
        run: |
          repo_owner="gplint"
          repo_name="gplint.github.io"
          event_type="trigger-workflow"

          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${PAT}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/gplint/gplint.github.io/dispatches \
          -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"unit\": false, \"integration\": true}}"
